# 04 — Visualisations des tables de la database and logs

In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path('..').resolve()))
from src.database import get_runs, get_evaluations, get_cases, get_prompts
import pandas as pd

DB_PATH = Path('..') / 'data' / 'database.sqlite'

### `Cases` table

In [2]:
display(pd.DataFrame(get_cases(DB_PATH)))

,id,image_path,source,ground_truth_label,split,notes
0,1,data/brutes/ABNORMAL-LUNG_00001_suspected_opac...,fkarimovv/abnormal-lung,suspected_opacity,external,Importé depuis ABNORMAL-LUNG_00001_suspected_o...
1,2,data/brutes/ABNORMAL-LUNG_00002_suspected_opac...,fkarimovv/abnormal-lung,suspected_opacity,external,Importé depuis ABNORMAL-LUNG_00002_suspected_o...
2,3,data/brutes/ABNORMAL-LUNG_00003_suspected_opac...,fkarimovv/abnormal-lung,suspected_opacity,external,Importé depuis ABNORMAL-LUNG_00003_suspected_o...
3,4,data/brutes/ABNORMAL-LUNG_00004_suspected_opac...,fkarimovv/abnormal-lung,suspected_opacity,external,Importé depuis ABNORMAL-LUNG_00004_suspected_o...
4,5,data/brutes/ABNORMAL-LUNG_00005_suspected_opac...,fkarimovv/abnormal-lung,suspected_opacity,external,Importé depuis ABNORMAL-LUNG_00005_suspected_o...
...,...,...,...,...,...,...
927,928,data/brutes/NORMAL-LUNG_00928_normal_567.jpg,fkarimovv/abnormal-lung,normal,external,Importé depuis NORMAL-LUNG_00928_normal_567.jpg
928,929,data/brutes/NORMAL-LUNG_00929_normal_568.jpg,fkarimovv/abnormal-lung,normal,external,Importé depuis NORMAL-LUNG_00929_normal_568.jpg
929,930,data/brutes/NORMAL-LUNG_00930_normal_569.jpg,fkarimovv/abnormal-lung,normal,external,Importé depuis NORMAL-LUNG_00930_normal_569.jpg
930,931,data/brutes/NORMAL-LUNG_00931_normal_570.jpg,fkarimovv/abnormal-lung,normal,external,Importé depuis NORMAL-LUNG_00931_normal_570.jpg
931,932,data/brutes/NORMAL-LUNG_00932_normal_571.jpg,fkarimovv/abnormal-lung,normal,external,Importé depuis NORMAL-LUNG_00932_normal_571.jpg

### `Runs` table

In [3]:
display(pd.DataFrame(get_runs(DB_PATH)))

,id,case_id,prompt_id,image_path,model_name,prediction_json,predicted_class,confidence,latency_ms,created_at
0,200,127,2,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.80,42357,2026-06-29 02:32:28
1,199,394,2,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.80,36220,2026-06-29 02:31:46
2,198,360,2,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.80,40955,2026-06-29 02:31:10
3,197,276,2,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",uncertain,0.20,46023,2026-06-29 02:30:29
4,196,108,2,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.80,33065,2026-06-29 02:29:43
...,...,...,...,...,...,...,...,...,...,...
195,5,616,1,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.95,53350,2026-06-29 00:25:12
196,4,466,1,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.95,38726,2026-06-29 00:24:19
197,3,500,1,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.95,38410,2026-06-29 00:23:40
198,2,640,1,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.95,47196,2026-06-29 00:23:01
199,1,17,1,C:\Users\auber.MSI\Projets\TD-Mastercamp\Solut...,medgemma-4b-it,"{""image_quality"": ""good"", ""predicted_class"": ""...",normal,0.95,52971,2026-06-29 00:22:14

### `Evaluations` Table

In [4]:
display(pd.DataFrame(get_evaluations(DB_PATH)))

,case_id,run_id,evaluation_id,prompt_id,prompt_name,prompt_version,ground_truth_label,predicted_class,confidence,latency
0,17,1,1,1,baseline,v0,suspected_opacity,normal,0.95,52971
1,29,83,83,1,baseline,v0,suspected_opacity,normal,0.95,35864
2,34,50,50,1,baseline,v0,suspected_opacity,normal,0.95,39044
3,37,55,55,1,baseline,v0,suspected_opacity,normal,0.80,44824
4,72,62,62,1,baseline,v0,suspected_opacity,normal,0.95,35904
...,...,...,...,...,...,...,...,...,...,...
195,849,159,159,2,improved,v1,normal,normal,0.80,37080
196,852,182,182,2,improved,v1,normal,normal,0.80,41933
197,879,130,130,2,improved,v1,normal,normal,0.80,41835
198,884,195,195,2,improved,v1,normal,normal,0.80,39508
199,890,143,143,2,improved,v1,normal,normal,0.80,33609

### `Prompts` table

In [5]:
display(pd.DataFrame(get_prompts(DB_PATH)))

,id,prompt_name,prompt_version,prompt_text,created_at
0,1,baseline,v0,You are an educational radiology assistant for...,2026-06-28 23:42:14
1,2,improved,v1,You are an educational radiology assistant for...,2026-06-28 23:42:14